package main;




import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import compilador.arbol_abstracto.otros.Estatuto;
import compilador.arbol_abstracto.otros.Programa;
import compilador.arbol_abstracto.otros.SemanticException;
import compilador.codigo_objeto.GeneracionCodigoObjeto;
import compilador.compilador1.Parser;
import compilador.compilador1.ParseException;
import compilador.compilador1.TokenMgrError;
import compilador.gui.JTextFieldLimit;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;


public class Menu extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    /**
     * Archivo fuente seleccionado por el usuario
     */
    private File archivoMostrado = new File(System.getProperty("user.dir") + File.separator + "hola.txt");
    /**
     * Canal de Entradade la variable acrchivoMostrado
     */
    private ObjectInputStream archivoEntrada;
    /**
     * Canal de Salida de la variable acrchivoMostrado
     */
    private ObjectOutputStream archivoSalida;

    /** Creates new form Menu */
    public Menu() {
        initComponents();
        JTextFieldLimit pa = new JTextFieldLimit(areaTexto);
        areaTexto.setDocument(pa);
       
        areaTexto.setText("int a;\n" +
"int b;\n" +
"if(a==b)\n" +
"	a = b;\n" +
"else\n" +
"	b = a;");
        boolean van = true;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoArbol = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoCodigoIntermedio = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 35));

        jButton1.setMnemonic('A');
        jButton1.setText("Abrir");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setMnemonic('G');
        jButton2.setText("Guardar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setMnemonic('N');
        jButton3.setText("Nuevo");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.add(jSeparator1);

        jButton4.setMnemonic('C');
        jButton4.setText("Compilar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setMnemonic('S');
        jButton5.setText("Salir");
        jButton5.setFocusable(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton5.setMaximumSize(new java.awt.Dimension(65, 39));
        jButton5.setMinimumSize(new java.awt.Dimension(65, 39));
        jButton5.setPreferredSize(new java.awt.Dimension(65, 39));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Codigo Fuente [ Compiler ]", jPanel3);

        campoArbol.setColumns(20);
        campoArbol.setRows(5);
        jScrollPane2.setViewportView(campoArbol);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("   [ Arbol Generado ]   ", jPanel4);

        campoCodigoIntermedio.setColumns(20);
        campoCodigoIntermedio.setRows(5);
        jScrollPane3.setViewportView(campoCodigoIntermedio);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("   [ Codigo Intermedio ]   ", jPanel5);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(788, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    if(!cargarFuente()){
        return;
    }
    try {
        MostrarFuente();
    } catch (IOException io) {
        JOptionPane.showMessageDialog(this, "Se genero un error al cargar el archivo\n\n" + io);
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    try {
        guardarFichero();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Se genero un error al guardar el archivo");
    }

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    areaTexto.setText("");
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    try {
        compilar();
        mostrarArbol(Programa.getEstatutos());
        String outputPath =  System.getProperty("user.dir") + File.separator + "salida.txt";
        new GeneracionCodigoObjeto(new File(outputPath),campoCodigoIntermedio, Programa.getEstatutos()).start();
//        Desktop dek = Desktop.getDesktop();
//        dek.open(new File("C:\\salida.txt"));
    }
    catch(ParseException parse){
        JOptionPane.showMessageDialog(this, "[ParseException] - Error de compilacion\n\n"+parse.getMessage());
        parse.printStackTrace();
    }
    catch(TokenMgrError mgr){
        JOptionPane.showMessageDialog(this, "[TokenMgrError] - Error de compilacion\n\n"+mgr.getMessage());
        mgr.printStackTrace();
    }
    catch(SemanticException sem){
        JOptionPane.showMessageDialog(this, "[Error Semantico] -"+sem);
        sem.printStackTrace();
    }
    catch (Exception io) {
        JOptionPane.showMessageDialog(this, "[IOException] - Error al guardar el archivo para su compilacion\n\n"+io);
        io.printStackTrace();
    }finally{
        Programa.getEstatutos().clear();
        Programa.getListaStatement().clear();
        Programa.getListaVariables().clear();
        Programa.getEstatutos().clear();
    }
}//GEN-LAST:event_jButton4ActionPerformed

    private void mostrarArbol(List<Estatuto> lista){
        campoArbol.setText("");
        for (Estatuto estatuto : lista) {
            campoArbol.append(estatuto.toString());
        }
    }

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_jButton5ActionPerformed
   
    private boolean compilar()throws IOException,  ParseException, SemanticException{
        String outputPath = System.getProperty("user.dir") + File.separator + "default.txt";
        File direccion = new File(outputPath);
        if(direccion.exists()){
            direccion.delete();
        }
        direccion.createNewFile();
        
        BufferedWriter buf = new BufferedWriter(new FileWriter(direccion));
        buf.write(areaTexto.getText());
        buf.close();
        
        FileInputStream stream = new FileInputStream(direccion);
        
        if(true){
            Parser oscar = new Parser(stream);
            oscar.programa();
        }else{
            JOptionPane.showMessageDialog(this, "Para continuar seleccione el compilador a utilizar");
            return false;
        }

        JOptionPane.showMessageDialog(this, "Compilacion Terminada con Exito");
        return true;
    }
    
    private void guardarFichero()throws IOException{
        String path = System.getProperty("user.dir");
        JFileChooser selector = new JFileChooser(new File(path));
        int op = selector.showSaveDialog(this);
        
        if( op !=JFileChooser.APPROVE_OPTION){
            return;
        }
        
        File direccion = selector.getSelectedFile();
        try {
            direccion = new File(direccion.getAbsolutePath()+".o++");
            direccion.createNewFile();
        } catch (IOException io) {            
            JOptionPane.showMessageDialog(this, "Se genero un error al crear el fichero nuevo\n\n"+io);
            return;
        }
        
        BufferedWriter buf = new BufferedWriter(new FileWriter(direccion));
        StringTokenizer token = new StringTokenizer(areaTexto.getText(),"\n");
        while(token.hasMoreTokens()){
            String linea = token.nextToken();
            buf.write(linea+"$");
        }
        buf.close();
    }

    /**
     * Metodo encargado de leer de disco el archivo fuente
     * @return regresa true si se selecciono un archivo, false de lo contrario
     */
    private boolean cargarFuente(){
        String initPath = System.getProperty("user.dir");
        JFileChooser selector = new JFileChooser( new File(initPath));
        selector.setMultiSelectionEnabled(false);
        int op = selector.showOpenDialog(this);
        
        if(op != JFileChooser.OPEN_DIALOG){
            return false;        
        }

        archivoMostrado = selector.getSelectedFile();
        return true;
    }

    /**
     * Metodo encargado de mostrar la el archivo fuente en pantalla
     */
    private void MostrarFuente()throws IOException{
        areaTexto.setText("");
        java.io.BufferedReader reader = new BufferedReader(new FileReader(archivoMostrado));
        
        String linea = reader.readLine();
        while(linea!=null){
            StringTokenizer token = new StringTokenizer(linea,"\n$");
            while(token.hasMoreTokens()){
                areaTexto.append(token.nextToken()+"\n");
            }
            linea = reader.readLine();
        }
        
        reader.close();
    }
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea campoArbol;
    private javax.swing.JTextArea campoCodigoIntermedio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
